import 'dart:convert';

/// Chapters [from]..[to] of one book.
class PlanReading {
  const PlanReading(this.book, this.from, this.to);

  final String book;
  final int from;
  final int to;
}

/// A bundled reading plan (generated by pipeline/build_plans.py).
class ReadingPlan {
  const ReadingPlan({required this.id, required this.name, required this.description, required this.days});

  final String id;
  final Map<String, String> name; // by language code
  final Map<String, String> description;
  final List<List<PlanReading>> days;

  int get length => days.length;

  String nameFor(String lang) => name[lang] ?? name['en']!;
  String descriptionFor(String lang) => description[lang] ?? description['en']!;

  /// Readings for a 1-based [day].
  List<PlanReading> readingsFor(int day) => days[day - 1];
}

List<ReadingPlan> parsePlans(String source) {
  final data = jsonDecode(source) as Map<String, dynamic>;
  return [
    for (final p in data['plans'] as List)
      ReadingPlan(
        id: p['id'] as String,
        name: Map<String, String>.from(p['name'] as Map),
        description: Map<String, String>.from(p['description'] as Map),
        days: [
          for (final day in p['days'] as List)
            [for (final r in day as List) PlanReading(r['b'] as String, r['f'] as int, r['t'] as int)],
        ],
      ),
  ];
}

/// Progress of a started plan.
class PlanProgress {
  const PlanProgress({required this.plan, required this.startedAt, required this.completed, required this.today});

  final ReadingPlan plan;
  final DateTime startedAt;
  final Set<int> completed; // 1-based days
  final DateTime today;

  /// The plan day matching today's date (1 on the start day), capped at the
  /// plan length.
  int get scheduledDay {
    final start = DateTime(startedAt.year, startedAt.month, startedAt.day);
    final now = DateTime(today.year, today.month, today.day);
    // Count calendar days, robust to daylight-saving changes.
    final days = DateTime.utc(
      now.year,
      now.month,
      now.day,
    ).difference(DateTime.utc(start.year, start.month, start.day)).inDays;
    return (days + 1).clamp(1, plan.length);
  }

  /// First day not yet completed (what "today's reading" shows), or null when
  /// the plan is finished.
  int? get nextDay {
    for (var d = 1; d <= plan.length; d++) {
      if (!completed.contains(d)) return d;
    }
    return null;
  }

  bool get finished => nextDay == null;

  /// Scheduled days up to today that are not completed.
  int get behind => [for (var d = 1; d <= scheduledDay; d++) d].where((d) => !completed.contains(d)).length;

  double get fraction => completed.length / plan.length;
}
