import 'dart:convert';

/// Chapters [from]..[to] of one book.
class PlanReading {
  const PlanReading(this.book, this.from, this.to);

  final String book;
  final int from;
  final int to;
}

/// How long a plan runs; the plans screen groups plans by it.
enum PlanPeriod {
  week(7),
  month(31),
  threeMonths(92),
  sixMonths(183),
  year(366);

  const PlanPeriod(this.maxDays);

  /// Longest plan in this period, in days.
  final int maxDays;

  /// The shortest period a plan of [days] fits in (a 60-day plan is a
  /// three-month plan).
  static PlanPeriod of(int days) => values.firstWhere((p) => days <= p.maxDays, orElse: () => year);
}

/// How demanding a plan's daily reading is.
enum PlanPace {
  light,
  steady,
  intensive;

  static PlanPace of(int minutesPerDay) => minutesPerDay < lightBelow
      ? light
      : minutesPerDay <= steadyUpTo
      ? steady
      : intensive;

  static const lightBelow = 10;
  static const steadyUpTo = 20;
}

/// A bundled reading plan (generated by pipeline/build_plans.py).
class ReadingPlan {
  const ReadingPlan({
    required this.id,
    required this.name,
    required this.description,
    required this.days,
    this.minutesPerDay,
    this.focus = const {},
    this.weekdays,
    this.start,
    this.carriedChapters = 0,
    this.custom = false,
  });

  final String id;
  final Map<String, String> name; // by language code
  final Map<String, String> description;
  final List<List<PlanReading>> days;

  /// Estimated reading time per day (null for plans without an estimate).
  final int? minutesPerDay;

  /// What the plan reads: "all", "ot", "nt", "gospels", "wisdom".
  final Set<String> focus;

  /// Weekdays with a reading (DateTime.monday..sunday); null means every day.
  final Set<int>? weekdays;

  /// First reading day, when the plan sets its own (plans you build may start
  /// later); otherwise the day the plan was started.
  final DateTime? start;

  /// Chapters read before the plan was last re-planned (counted as progress).
  final int carriedChapters;

  /// Built by the user (can be re-planned and deleted, not restarted).
  final bool custom;

  int get chapterCount => [for (final d in days) ...d].fold(0, (n, r) => n + r.to - r.from + 1);

  int chaptersOnDay(int day) => readingsFor(day).fold(0, (n, r) => n + r.to - r.from + 1);

  int get length => days.length;

  PlanPeriod get period => PlanPeriod.of(length);

  PlanPace? get pace => minutesPerDay == null ? null : PlanPace.of(minutesPerDay!);

  String nameFor(String lang) => name[lang] ?? name['en']!;
  String descriptionFor(String lang) => description[lang] ?? description['en']!;

  /// Readings for a 1-based [day].
  List<PlanReading> readingsFor(int day) => days[day - 1];
}

List<ReadingPlan> parsePlans(String source) {
  final data = jsonDecode(source) as Map<String, dynamic>;
  return [
    for (final p in data['plans'] as List)
      ReadingPlan(
        id: p['id'] as String,
        name: Map<String, String>.from(p['name'] as Map),
        description: Map<String, String>.from(p['description'] as Map),
        minutesPerDay: (p['minutes'] as num?)?.toInt(),
        focus: {...?(p['focus'] as List?)?.cast<String>()},
        days: [
          for (final day in p['days'] as List)
            [for (final r in day as List) PlanReading(r['b'] as String, r['f'] as int, r['t'] as int)],
        ],
      ),
  ];
}

/// Progress of a started plan.
class PlanProgress {
  const PlanProgress({required this.plan, required this.startedAt, required this.completed, required this.today});

  final ReadingPlan plan;
  final DateTime startedAt;
  final Set<int> completed; // 1-based days
  final DateTime today;

  /// The plan day matching today's date (1 on the start day), capped at the
  /// plan length. Only reading weekdays count when the plan has them.
  int get scheduledDay {
    final start = plan.start ?? startedAt;
    final weekdays = plan.weekdays;
    final days = weekdays == null ? calendarDaysBetween(start, today) + 1 : readingDaysThrough(start, today, weekdays);
    return days.clamp(1, plan.length);
  }

  /// First day not yet completed (what "today's reading" shows), or null when
  /// the plan is finished.
  int? get nextDay {
    for (var d = 1; d <= plan.length; d++) {
      if (!completed.contains(d)) return d;
    }
    return null;
  }

  bool get finished => nextDay == null;

  /// Scheduled days up to today that are not completed.
  int get behind => [for (var d = 1; d <= scheduledDay; d++) d].where((d) => !completed.contains(d)).length;

  double get fraction {
    if (plan.carriedChapters == 0) return completed.length / plan.length;
    final done = plan.carriedChapters + completed.fold(0, (n, d) => n + plan.chaptersOnDay(d));
    return done / (plan.carriedChapters + plan.chapterCount);
  }
}

DateTime _date(DateTime d) => DateTime.utc(d.year, d.month, d.day);

/// Whole calendar days from [a] to [b] (local dates; daylight saving safe).
int calendarDaysBetween(DateTime a, DateTime b) => _date(b).difference(_date(a)).inDays;

/// Reading days (dates whose weekday is in [weekdays]) from [start] through
/// [end], inclusive; 0 when [end] is before [start].
int readingDaysThrough(DateTime start, DateTime end, Set<int> weekdays) {
  final total = calendarDaysBetween(start, end) + 1;
  if (total <= 0 || weekdays.isEmpty) return 0;
  final weeks = total ~/ 7;
  var n = weeks * weekdays.length;
  final first = _date(start);
  for (var i = weeks * 7; i < total; i++) {
    if (weekdays.contains(first.add(Duration(days: i)).weekday)) n++;
  }
  return n;
}

/// The first [count] reading dates from [start] (UTC midnights).
List<DateTime> readingDates(DateTime start, Set<int> weekdays, int count) {
  if (weekdays.isEmpty) return const [];
  final out = <DateTime>[];
  for (var d = _date(start); out.length < count; d = d.add(const Duration(days: 1))) {
    if (weekdays.contains(d.weekday)) out.add(d);
  }
  return out;
}
